Terminal|bash
HTOP|htop
Python|python3
Midnight Commander|mc
Nano|nano
Vim|vim
System Info|bash -c "echo; free -h; echo; uptime; echo; echo Press Enter...; read"
Reboot|echo 2 | sudo -S reboot
Poweroff|echo 2 | sudo -S poweroff
